"""itmentorsoft-persistence — public API.

External applications can import any class directly from the package root:

    from itmentorsoft_persistence import User, UserRepository, PostgresUserMapper
"""

# ---------------------------------------------------------------------------
# Database session & engine
# ---------------------------------------------------------------------------
from .postgresql_database_session import (
    AsyncSessionLocal,
    Base,
    engine,
    ensure_database_exists,
    get_db,
    init_db,
)

# ---------------------------------------------------------------------------
# Entities (SQLAlchemy models)
# ---------------------------------------------------------------------------
from .models import (
    AssessmentAnswerEntity,
    AssessmentEntity,
    AssessmentQualificationEntity,
    AssessmentQuizEntity,
    ClassificationResultEntity,
    ContentRating,
    LearningPathContentEntity,
    LearningPathEntity,
    QuestionEntity,
    QuestionReviewEntity,
    QuestionRubricScoreEntity,
    RecoveryTokenEntity,
    RefreshTokenEntity,
    ResourceContentEntity,
    RoleEntity,
    UserEntity,
)

# ---------------------------------------------------------------------------
# DTOs
# ---------------------------------------------------------------------------
from .dto import (
    AssignRoleToUserCommand,
    Assessment,
    AssessmentAnswer,
    AssessmentQuiz,
    AssessmentSummary,
    CategorySummary,
    ClassificationResult,
    CompleteUserResponse,
    ContentByTopic,
    ContentCategory,
    EvaluativeQuestion,
    GetContentsByCategoryPaginationRequest,
    GetContentsByCategoryTopicPaginationRequest,
    GetContentsByTitlePaginationRequest,
    GetContentsByTopicPaginationRequest,
    HistoricalResult,
    LearningPath,
    LearningPathProgress,
    LearningPathProgressResponse,
    LearningPathResponse,
    PaginatedAssessmentSummary,
    PaginatedQuestionsResult,
    PaginatedResourceContentResult,
    PaginatedStudentSummary,
    QualifierResult,
    Question,
    QuestionBuilder,
    QuestionDetails,
    QuestionDifficulty,
    QuestionReview,
    QuestionRubricScore,
    QuestionStatus,
    RateContent,
    RecoveryTokenInfo,
    ResourceContent,
    ResourceContentBuilder,
    ResourceContentRating,
    ResourceContentResponse,
    Role,
    RubricScore,
    StudentAnswerScore,
    StudentAssessmentResult,
    StudentBasicSummary,
    StudentKnowledgeProfile,
    StudentProgress,
    StudentProgressDetail,
    StudentSummary,
    TopContentOrder,
    TopicResult,
    UpdateResourceContentRequest,
    User,
    UserResponse,
    UserRole,
    UserStatus,
    UserRecoveryTokenResponse,
)

# ---------------------------------------------------------------------------
# Mappers
# ---------------------------------------------------------------------------
from .mappers import (
    PostgresAssessmentAnswerMapper,
    PostgresAssessmentMapper,
    PostgresAssessmentQualificationMapper,
    PostgresClassificationResultMapper,
    PostgresLearningPathMapper,
    PostgresQuestionMapper,
    PostgresRecoveryTokenMapper,
    PostgresReportMapper,
    PostgresRoleMapper,
    PostgresTopicResultMapper,
    PostgresUserMapper,
    RateContentMapper,
    ResourceContentMapper,
)

# ---------------------------------------------------------------------------
# Repositories
# ---------------------------------------------------------------------------
from .repositories import (
    AssessmentRepository,
    LearningPathRepository,
    QuestionAssessmentRepository,
    QuestionRepository,
    RefreshTokenData,
    RefreshTokenInfo,
    RefreshTokenRepository,
    ReportRepository,
    ResourceContentRepository,
    RoleRepository,
    TotalActiveUsers,
    UserRecoveryTokenRepository,
    UserRepository,
)

__all__ = [
    # --- Database session & engine ---
    "AsyncSessionLocal",
    "Base",
    "engine",
    "ensure_database_exists",
    "get_db",
    "init_db",
    # --- Entities ---
    "AssessmentAnswerEntity",
    "AssessmentEntity",
    "AssessmentQualificationEntity",
    "AssessmentQuizEntity",
    "ClassificationResultEntity",
    "ContentRating",
    "LearningPathContentEntity",
    "LearningPathEntity",
    "QuestionEntity",
    "QuestionReviewEntity",
    "QuestionRubricScoreEntity",
    "RecoveryTokenEntity",
    "RefreshTokenEntity",
    "ResourceContentEntity",
    "RoleEntity",
    "UserEntity",
    # --- DTOs ---
    "AssignRoleToUserCommand",
    "Assessment",
    "AssessmentAnswer",
    "AssessmentQuiz",
    "AssessmentSummary",
    "CategorySummary",
    "ClassificationResult",
    "CompleteUserResponse",
    "ContentByTopic",
    "ContentCategory",
    "EvaluativeQuestion",
    "GetContentsByCategoryPaginationRequest",
    "GetContentsByCategoryTopicPaginationRequest",
    "GetContentsByTitlePaginationRequest",
    "GetContentsByTopicPaginationRequest",
    "HistoricalResult",
    "LearningPath",
    "LearningPathProgress",
    "LearningPathProgressResponse",
    "LearningPathResponse",
    "PaginatedAssessmentSummary",
    "PaginatedQuestionsResult",
    "PaginatedResourceContentResult",
    "PaginatedStudentSummary",
    "QualifierResult",
    "Question",
    "QuestionBuilder",
    "QuestionDetails",
    "QuestionDifficulty",
    "QuestionReview",
    "QuestionRubricScore",
    "QuestionStatus",
    "RateContent",
    "RecoveryTokenInfo",
    "ResourceContent",
    "ResourceContentBuilder",
    "ResourceContentRating",
    "ResourceContentResponse",
    "Role",
    "RubricScore",
    "StudentAnswerScore",
    "StudentAssessmentResult",
    "StudentBasicSummary",
    "StudentKnowledgeProfile",
    "StudentProgress",
    "StudentProgressDetail",
    "StudentSummary",
    "TopContentOrder",
    "TopicResult",
    "UpdateResourceContentRequest",
    "User",
    "UserRecoveryTokenResponse",
    "UserResponse",
    "UserRole",
    "UserStatus",
    # --- Mappers ---
    "PostgresAssessmentAnswerMapper",
    "PostgresAssessmentMapper",
    "PostgresAssessmentQualificationMapper",
    "PostgresClassificationResultMapper",
    "PostgresLearningPathMapper",
    "PostgresQuestionMapper",
    "PostgresRecoveryTokenMapper",
    "PostgresReportMapper",
    "PostgresRoleMapper",
    "PostgresTopicResultMapper",
    "PostgresUserMapper",
    "RateContentMapper",
    "ResourceContentMapper",
    # --- Repositories ---
    "AssessmentRepository",
    "LearningPathRepository",
    "QuestionAssessmentRepository",
    "QuestionRepository",
    "RefreshTokenData",
    "RefreshTokenInfo",
    "RefreshTokenRepository",
    "ReportRepository",
    "ResourceContentRepository",
    "RoleRepository",
    "TotalActiveUsers",
    "UserRecoveryTokenRepository",
    "UserRepository",
]
