"""agrega_columna_primera_version

Revision ID: 27b70919b8d0
Revises: dadca38ade61
Create Date: 2026-09-28 07:14:58.039916

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "27b70919b8d0"
down_revision: Union[str, Sequence[str], None] = "dadca38ade61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("root_version_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "root_version_id")
    # ### end Alembic commands ###
