"""Agrega campos para control de acceso

Revision ID: 7649bf1a37b4
Revises: b565fdffbc88
Create Date: 2026-09-06 06:47:23.061320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7649bf1a37b4'
down_revision: Union[str, Sequence[str], None] = 'b565fdffbc88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_access', sa.Column('temporary_block_expiration', sa.Float(), nullable=False))
    op.add_column('user_access', sa.Column('is_temporarily_blocked', sa.Boolean(), nullable=False))
    op.add_column('user_access', sa.Column('definitively_blocked', sa.Boolean(), nullable=False))
    op.drop_column('user_access', 'blocked')
    op.drop_column('user_access', 'block_time_seconds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_access', sa.Column('block_time_seconds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_access', sa.Column('blocked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user_access', 'definitively_blocked')
    op.drop_column('user_access', 'is_temporarily_blocked')
    op.drop_column('user_access', 'temporary_block_expiration')
    # ### end Alembic commands ###
