"""crea_indices_en_preguntas

Revision ID: 7c2c4fcb3dc1
Revises: 7649bf1a37b4
Create Date: 2026-09-27 07:19:05.421350

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7c2c4fcb3dc1"
down_revision: Union[str, Sequence[str], None] = "7649bf1a37b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_id"), table_name="questions")
    op.create_index(op.f("ix_questions_id"), "questions", ["id"], unique=True)
    op.create_index(
        op.f("ix_questions_classification"),
        "questions",
        ["classification"],
        unique=False,
    )
    op.create_index(
        op.f("ix_questions_version"), "questions", ["version"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_version"), table_name="questions")
    op.drop_index(op.f("ix_questions_classification"), table_name="questions")
    op.drop_index(op.f("ix_questions_id"), table_name="questions")
    op.create_index(op.f("ix_questions_id"), "questions", ["id"], unique=False)
    # ### end Alembic commands ###
