"""Initial migration

Revision ID: 95fd08243f33
Revises: 
Create Date: 2026-08-31 17:55:27.127094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95fd08243f33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('related_topics', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_id'), 'contents', ['id'], unique=False)
    op.create_index(op.f('ix_contents_title'), 'contents', ['title'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('definition', sa.String(), nullable=False),
    sa.Column('simple_explanation', sa.String(), nullable=False),
    sa.Column('correct_sample', sa.String(), nullable=False),
    sa.Column('wrong_sample', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('common_misconceptions', sa.String(), nullable=False),
    sa.Column('semantic_keywords', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_text'), 'questions', ['text'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('question_rubric_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_rubric_scores_question_id'), 'question_rubric_scores', ['question_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_user_id'), 'assessments', ['user_id'], unique=False)
    op.create_table('content_ratings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_ratings_id'), 'content_ratings', ['id'], unique=False)
    op.create_table('learning_paths',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_id'), 'learning_paths', ['id'], unique=False)
    op.create_index(op.f('ix_learning_paths_topic'), 'learning_paths', ['topic'], unique=False)
    op.create_index(op.f('ix_learning_paths_user_id'), 'learning_paths', ['user_id'], unique=False)
    op.create_table('question_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('review_comments', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_reviews_id'), 'question_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_question_reviews_question_id'), 'question_reviews', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_reviews_reviewer_id'), 'question_reviews', ['reviewer_id'], unique=False)
    op.create_table('topic_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_results_topic'), 'topic_results', ['topic'], unique=False)
    op.create_index(op.f('ix_topic_results_user_id'), 'topic_results', ['user_id'], unique=False)
    op.create_table('user_recovery_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expitation_time', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_recovery_tokens_id'), 'user_recovery_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_user_recovery_tokens_token'), 'user_recovery_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_user_recovery_tokens_user_id'), 'user_recovery_tokens', ['user_id'], unique=False)
    op.create_table('user_refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expiration_time', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_refresh_tokens_id'), 'user_refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_user_refresh_tokens_token'), 'user_refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_user_refresh_tokens_user_id'), 'user_refresh_tokens', ['user_id'], unique=False)
    op.create_table('assessment_answers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_answers_assessment_id'), 'assessment_answers', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_answers_id'), 'assessment_answers', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_answers_question_id'), 'assessment_answers', ['question_id'], unique=False)
    op.create_table('assessment_quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_quizzes_assessment_id'), 'assessment_quizzes', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_quizzes_question_id'), 'assessment_quizzes', ['question_id'], unique=False)
    op.create_table('classification_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('feedback', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_results_assessment_id'), 'classification_results', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_classification_results_classification'), 'classification_results', ['classification'], unique=False)
    op.create_index(op.f('ix_classification_results_user_id'), 'classification_results', ['user_id'], unique=False)
    op.create_table('learning_path_contents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('learning_path_id', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_path_contents_content_id'), 'learning_path_contents', ['content_id'], unique=False)
    op.create_index(op.f('ix_learning_path_contents_id'), 'learning_path_contents', ['id'], unique=False)
    op.create_index(op.f('ix_learning_path_contents_learning_path_id'), 'learning_path_contents', ['learning_path_id'], unique=False)
    op.create_table('assessment_qualifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('answer_id', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(), nullable=False),
    sa.Column('question_topic', sa.String(), nullable=False),
    sa.Column('question_difficulty', sa.String(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['assessment_answers.id'], ),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'user_id', 'assessment_id', name='uq_assessment_qualification')
    )
    op.create_index(op.f('ix_assessment_qualifications_answer_id'), 'assessment_qualifications', ['answer_id'], unique=False)
    op.create_index(op.f('ix_assessment_qualifications_assessment_id'), 'assessment_qualifications', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_qualifications_id'), 'assessment_qualifications', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_qualifications_question_id'), 'assessment_qualifications', ['question_id'], unique=False)
    op.create_index(op.f('ix_assessment_qualifications_user_id'), 'assessment_qualifications', ['user_id'], unique=False)
    op.create_table('assessment_misconceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.String(), nullable=False),
    sa.Column('misconception', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['qualification_id'], ['assessment_qualifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_misconceptions_qualification_id'), 'assessment_misconceptions', ['qualification_id'], unique=False)
    op.create_table('assessment_qualification_key_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.String(), nullable=False),
    sa.Column('key_concept', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['qualification_id'], ['assessment_qualifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_qualification_key_concepts_qualification_id'), 'assessment_qualification_key_concepts', ['qualification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_qualification_key_concepts_qualification_id'), table_name='assessment_qualification_key_concepts')
    op.drop_table('assessment_qualification_key_concepts')
    op.drop_index(op.f('ix_assessment_misconceptions_qualification_id'), table_name='assessment_misconceptions')
    op.drop_table('assessment_misconceptions')
    op.drop_index(op.f('ix_assessment_qualifications_user_id'), table_name='assessment_qualifications')
    op.drop_index(op.f('ix_assessment_qualifications_question_id'), table_name='assessment_qualifications')
    op.drop_index(op.f('ix_assessment_qualifications_id'), table_name='assessment_qualifications')
    op.drop_index(op.f('ix_assessment_qualifications_assessment_id'), table_name='assessment_qualifications')
    op.drop_index(op.f('ix_assessment_qualifications_answer_id'), table_name='assessment_qualifications')
    op.drop_table('assessment_qualifications')
    op.drop_index(op.f('ix_learning_path_contents_learning_path_id'), table_name='learning_path_contents')
    op.drop_index(op.f('ix_learning_path_contents_id'), table_name='learning_path_contents')
    op.drop_index(op.f('ix_learning_path_contents_content_id'), table_name='learning_path_contents')
    op.drop_table('learning_path_contents')
    op.drop_index(op.f('ix_classification_results_user_id'), table_name='classification_results')
    op.drop_index(op.f('ix_classification_results_classification'), table_name='classification_results')
    op.drop_index(op.f('ix_classification_results_assessment_id'), table_name='classification_results')
    op.drop_table('classification_results')
    op.drop_index(op.f('ix_assessment_quizzes_question_id'), table_name='assessment_quizzes')
    op.drop_index(op.f('ix_assessment_quizzes_assessment_id'), table_name='assessment_quizzes')
    op.drop_table('assessment_quizzes')
    op.drop_index(op.f('ix_assessment_answers_question_id'), table_name='assessment_answers')
    op.drop_index(op.f('ix_assessment_answers_id'), table_name='assessment_answers')
    op.drop_index(op.f('ix_assessment_answers_assessment_id'), table_name='assessment_answers')
    op.drop_table('assessment_answers')
    op.drop_index(op.f('ix_user_refresh_tokens_user_id'), table_name='user_refresh_tokens')
    op.drop_index(op.f('ix_user_refresh_tokens_token'), table_name='user_refresh_tokens')
    op.drop_index(op.f('ix_user_refresh_tokens_id'), table_name='user_refresh_tokens')
    op.drop_table('user_refresh_tokens')
    op.drop_index(op.f('ix_user_recovery_tokens_user_id'), table_name='user_recovery_tokens')
    op.drop_index(op.f('ix_user_recovery_tokens_token'), table_name='user_recovery_tokens')
    op.drop_index(op.f('ix_user_recovery_tokens_id'), table_name='user_recovery_tokens')
    op.drop_table('user_recovery_tokens')
    op.drop_index(op.f('ix_topic_results_user_id'), table_name='topic_results')
    op.drop_index(op.f('ix_topic_results_topic'), table_name='topic_results')
    op.drop_table('topic_results')
    op.drop_index(op.f('ix_question_reviews_reviewer_id'), table_name='question_reviews')
    op.drop_index(op.f('ix_question_reviews_question_id'), table_name='question_reviews')
    op.drop_index(op.f('ix_question_reviews_id'), table_name='question_reviews')
    op.drop_table('question_reviews')
    op.drop_index(op.f('ix_learning_paths_user_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_topic'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_content_ratings_id'), table_name='content_ratings')
    op.drop_table('content_ratings')
    op.drop_index(op.f('ix_assessments_user_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_question_rubric_scores_question_id'), table_name='question_rubric_scores')
    op.drop_table('question_rubric_scores')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_questions_text'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_contents_title'), table_name='contents')
    op.drop_index(op.f('ix_contents_id'), table_name='contents')
    op.drop_table('contents')
    # ### end Alembic commands ###
