"""agrega_columna_version_previa

Revision ID: dadca38ade61
Revises: 7c2c4fcb3dc1
Create Date: 2026-09-28 06:52:10.257896

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "dadca38ade61"
down_revision: Union[str, Sequence[str], None] = "7c2c4fcb3dc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions", sa.Column("previous_version_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "previous_version_id")
    # ### end Alembic commands ###
